# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@electron/get-1.12.4" = {
      name = "_at_electron_slash_get";
      packageName = "@electron/get";
      version = "1.12.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@electron/get/-/get-1.12.4.tgz";
        sha512 = "6nr9DbJPUR9Xujw6zD3y+rS95TyItEVM0NVjt1EehY2vUWfIgPiIPVHxCvaTS0xr2B+DRxovYVKbuOWqC35kjg==";
      };
    };
    "@sindresorhus/is-0.14.0" = {
      name = "_at_sindresorhus_slash_is";
      packageName = "@sindresorhus/is";
      version = "0.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sindresorhus/is/-/is-0.14.0.tgz";
        sha512 = "9NET910DNaIPngYnLLPeg+Ogzqsi9uM4mSboU5y6p8S5DzMTVEsJZrawi+BoDNUVBa2DhJqQYUFvMDfgU062LQ==";
      };
    };
    "@szmarczak/http-timer-1.1.2" = {
      name = "_at_szmarczak_slash_http-timer";
      packageName = "@szmarczak/http-timer";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@szmarczak/http-timer/-/http-timer-1.1.2.tgz";
        sha512 = "XIB2XbzHTN6ieIjfIMV9hlVcfPU26s2vafYWQcZHWXHOxiaRZYEDKEwdl129Zyg50+foYV2jCgtrqSA6qNuNSA==";
      };
    };
    "@types/glob-7.1.3" = {
      name = "_at_types_slash_glob";
      packageName = "@types/glob";
      version = "7.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/glob/-/glob-7.1.3.tgz";
        sha512 = "SEYeGAIQIQX8NN6LDKprLjbrd5dARM5EXsd8GI/A5l0apYI1fGMWgPHSe4ZKL4eozlAyI+doUE9XbYS4xCkQ1w==";
      };
    };
    "@types/minimatch-3.0.3" = {
      name = "_at_types_slash_minimatch";
      packageName = "@types/minimatch";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/minimatch/-/minimatch-3.0.3.tgz";
        sha512 = "tHq6qdbT9U1IRSGf14CL0pUlULksvY9OZ+5eEgl1N7t+OA3tGvNpxJCzuKQlsNgCVwbAs670L1vcVQi8j9HjnA==";
      };
    };
    "@types/node-14.14.35" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "14.14.35";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-14.14.35.tgz";
        sha512 = "Lt+wj8NVPx0zUmUwumiVXapmaLUcAk3yPuHCFVXras9k5VT9TdhJqKqGVUQCD60OTMCl0qxJ57OiTL0Mic3Iag==";
      };
    };
    "@types/yauzl-2.9.1" = {
      name = "_at_types_slash_yauzl";
      packageName = "@types/yauzl";
      version = "2.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/yauzl/-/yauzl-2.9.1.tgz";
        sha512 = "A1b8SU4D10uoPjwb0lnHmmu8wZhR9d+9o2PKBQT2jU5YPTKsxac6M2qGAdY7VcL+dHHhARVUDmeg0rOrcd9EjA==";
      };
    };
    "asar-3.0.3" = {
      name = "asar";
      packageName = "asar";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asar/-/asar-3.0.3.tgz";
        sha512 = "k7zd+KoR+n8pl71PvgElcoKHrVNiSXtw7odKbyNpmgKe7EGRF9Pnu3uLOukD37EvavKwVFxOUpqXTIZC5B5Pmw==";
      };
    };
    "at-least-node-1.0.0" = {
      name = "at-least-node";
      packageName = "at-least-node";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/at-least-node/-/at-least-node-1.0.0.tgz";
        sha512 = "+q/t7Ekv1EDY2l6Gda6LLiX14rU9TV20Wa3ofeQmwPFZbOMo9DXrLbOjFaaclkXKWidIaopwAObQDqwWtGUjqg==";
      };
    };
    "author-regex-1.0.0" = {
      name = "author-regex";
      packageName = "author-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/author-regex/-/author-regex-1.0.0.tgz";
        sha1 = "d08885be6b9bbf9439fe087c76287245f0a81450";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "base64-js-1.5.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz";
        sha512 = "AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==";
      };
    };
    "bluebird-3.7.2" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.7.2.tgz";
        sha512 = "XpNj6GDQzdfW+r2Wnn7xiSAd7TM3jzkxGXBGTtWKuSXv1xUV+azxAm8jdWZN06QTQk+2N2XB9jRDkvbmQmcRtg==";
      };
    };
    "boolean-3.0.2" = {
      name = "boolean";
      packageName = "boolean";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/boolean/-/boolean-3.0.2.tgz";
        sha512 = "RwywHlpCRc3/Wh81MiCKun4ydaIFyW5Ea6JbL6sRCVx5q5irDw7pMXBUFYF/jArQ6YrG36q0kpovc9P/Kd3I4g==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "buffer-alloc-1.2.0" = {
      name = "buffer-alloc";
      packageName = "buffer-alloc";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-alloc/-/buffer-alloc-1.2.0.tgz";
        sha512 = "CFsHQgjtW1UChdXgbyJGtnm+O/uLQeZdtbDo8mfUgYXCHSM1wgrVxXm6bSyrUuErEb+4sYVGCzASBRot7zyrow==";
      };
    };
    "buffer-alloc-unsafe-1.1.0" = {
      name = "buffer-alloc-unsafe";
      packageName = "buffer-alloc-unsafe";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-alloc-unsafe/-/buffer-alloc-unsafe-1.1.0.tgz";
        sha512 = "TEM2iMIEQdJ2yjPJoSIsldnleVaAk1oW3DBVUykyOLsEsFmEc9kn+SFFPz+gl54KQNxlDnAwCXosOS9Okx2xAg==";
      };
    };
    "buffer-crc32-0.2.13" = {
      name = "buffer-crc32";
      packageName = "buffer-crc32";
      version = "0.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.13.tgz";
        sha1 = "0d333e3f00eac50aa1454abd30ef8c2a5d9a7242";
      };
    };
    "buffer-fill-1.0.0" = {
      name = "buffer-fill";
      packageName = "buffer-fill";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-fill/-/buffer-fill-1.0.0.tgz";
        sha1 = "f8f78b76789888ef39f205cd637f68e702122b2c";
      };
    };
    "cacheable-request-6.1.0" = {
      name = "cacheable-request";
      packageName = "cacheable-request";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cacheable-request/-/cacheable-request-6.1.0.tgz";
        sha512 = "Oj3cAGPCqOZX7Rz64Uny2GYAZNliQSqfbePrgAQ1wKAihYmCUnraBtJtKcGR4xz7wF+LoJC+ssFZvv5BgF9Igg==";
      };
    };
    "chromium-pickle-js-0.2.0" = {
      name = "chromium-pickle-js";
      packageName = "chromium-pickle-js";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chromium-pickle-js/-/chromium-pickle-js-0.2.0.tgz";
        sha1 = "04a106672c18b085ab774d983dfa3ea138f22205";
      };
    };
    "clone-response-1.0.2" = {
      name = "clone-response";
      packageName = "clone-response";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone-response/-/clone-response-1.0.2.tgz";
        sha1 = "d1dc973920314df67fbeb94223b4ee350239e96b";
      };
    };
    "commander-5.1.0" = {
      name = "commander";
      packageName = "commander";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-5.1.0.tgz";
        sha512 = "P0CysNDQ7rtVw4QIQtm+MRxV66vKFSvlsQvGYXZWR3qFU0jlMKHZZZgw8e+8DSah4UDKMqnknRDQz+xuQXQ/Zg==";
      };
    };
    "compare-version-0.1.2" = {
      name = "compare-version";
      packageName = "compare-version";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/compare-version/-/compare-version-0.1.2.tgz";
        sha1 = "0162ec2d9351f5ddd59a9202cba935366a725080";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "config-chain-1.1.12" = {
      name = "config-chain";
      packageName = "config-chain";
      version = "1.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/config-chain/-/config-chain-1.1.12.tgz";
        sha512 = "a1eOIcu8+7lUInge4Rpf/n4Krkf3Dd9lqhljRzII1/Zno/kRtUWnznPO3jOKBmTEktkt3fkxisUcivoj0ebzoA==";
      };
    };
    "core-js-3.9.1" = {
      name = "core-js";
      packageName = "core-js";
      version = "3.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-3.9.1.tgz";
        sha512 = "gSjRvzkxQc1zjM/5paAmL4idJBFzuJoo+jDjF1tStYFMV2ERfD02HhahhCGXUyHxQRG4yFKVSdO6g62eoRMcDg==";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "debug-3.2.7" = {
      name = "debug";
      packageName = "debug";
      version = "3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.2.7.tgz";
        sha512 = "CFjzYYAi4ThfiQvizrFQevTTXHtnCqWfe7x1AhgEscTz6ZbLbfoLRLPugTQyBth6f8ZERVUSyWHFD/7Wu4t1XQ==";
      };
    };
    "debug-4.3.2" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.2.tgz";
        sha512 = "mOp8wKcvj7XxC78zLgw/ZA+6TSgkoE2C/ienthhRD298T7UNwAg9diBpLRxC0mOezLl4B0xV7M0cCO6P/O0Xhw==";
      };
    };
    "decompress-response-3.3.0" = {
      name = "decompress-response";
      packageName = "decompress-response";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-response/-/decompress-response-3.3.0.tgz";
        sha1 = "80a4dd323748384bfa248083622aedec982adff3";
      };
    };
    "defer-to-connect-1.1.3" = {
      name = "defer-to-connect";
      packageName = "defer-to-connect";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/defer-to-connect/-/defer-to-connect-1.1.3.tgz";
        sha512 = "0ISdNousHvZT2EiFlZeZAHBUvSxmKswVCEf8hW7KWgG4a8MVEu/3Vb6uWYozkjylyCxe0JBIiRB1jV45S70WVQ==";
      };
    };
    "define-properties-1.1.3" = {
      name = "define-properties";
      packageName = "define-properties";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-properties/-/define-properties-1.1.3.tgz";
        sha512 = "3MqfYKj2lLzdMSf8ZIZE/V+Zuy+BgD6f164e8K2w7dgnpKArBDerGYpM46IYYcjnkdPNMjPk9A6VFB8+3SKlXQ==";
      };
    };
    "detect-node-2.0.5" = {
      name = "detect-node";
      packageName = "detect-node";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-node/-/detect-node-2.0.5.tgz";
        sha512 = "qi86tE6hRcFHy8jI1m2VG+LaPUR1LhqDa5G8tVjuUXmOrpuAgqsA1pN0+ldgr3aKUH+QLI9hCY/OcRYisERejw==";
      };
    };
    "duplexer3-0.1.4" = {
      name = "duplexer3";
      packageName = "duplexer3";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer3/-/duplexer3-0.1.4.tgz";
        sha1 = "ee01dd1cac0ed3cbc7fdbea37dc0a8f1ce002ce2";
      };
    };
    "electron-is-accelerator-0.1.2" = {
      name = "electron-is-accelerator";
      packageName = "electron-is-accelerator";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-is-accelerator/-/electron-is-accelerator-0.1.2.tgz";
        sha1 = "509e510c26a56b55e17f863a4b04e111846ab27b";
      };
    };
    "electron-localshortcut-3.2.1" = {
      name = "electron-localshortcut";
      packageName = "electron-localshortcut";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-localshortcut/-/electron-localshortcut-3.2.1.tgz";
        sha512 = "DWvhKv36GsdXKnaFFhEiK8kZZA+24/yFLgtTwJJHc7AFgDjNRIBJZ/jq62Y/dWv9E4ypYwrVWN2bVrCYw1uv7Q==";
      };
    };
    "electron-notarize-1.0.0" = {
      name = "electron-notarize";
      packageName = "electron-notarize";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-notarize/-/electron-notarize-1.0.0.tgz";
        sha512 = "dsib1IAquMn0onCrNMJ6gtEIZn/azG8hZMCYOuZIMVMUeRMgBYHK1s5TK9P8xAcrAjh/2aN5WYHzgVSWX314og==";
      };
    };
    "electron-osx-sign-0.5.0" = {
      name = "electron-osx-sign";
      packageName = "electron-osx-sign";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-osx-sign/-/electron-osx-sign-0.5.0.tgz";
        sha512 = "icoRLHzFz/qxzDh/N4Pi2z4yVHurlsCAYQvsCSG7fCedJ4UJXBS6PoQyGH71IfcqKupcKeK7HX/NkyfG+v6vlQ==";
      };
    };
    "electron-packager-15.2.0" = {
      name = "electron-packager";
      packageName = "electron-packager";
      version = "15.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-packager/-/electron-packager-15.2.0.tgz";
        sha512 = "BaklTBRQy1JTijR3hi8XxHf/uo76rHbDCNM/eQHSblzE9C0NoNfOe86nPxB7y1u2jwlqoEJ4zFiHpTFioKGGRA==";
      };
    };
    "electron-squirrel-startup-1.0.0" = {
      name = "electron-squirrel-startup";
      packageName = "electron-squirrel-startup";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-squirrel-startup/-/electron-squirrel-startup-1.0.0.tgz";
        sha1 = "19b4e55933fa0ef8f556784b9c660f772546a0b8";
      };
    };
    "encodeurl-1.0.2" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.2.tgz";
        sha1 = "ad3ff4c86ec2d029322f5a02c3a9a606c95b3f59";
      };
    };
    "end-of-stream-1.4.4" = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.4.tgz";
        sha512 = "+uw1inIHVPQoaVuHzRyXd21icM+cnt4CzD5rW+NC1wjOUSTOs+Te7FOv7AhN7vS9x/oIyhLP5PR1H+phQAHu5Q==";
      };
    };
    "env-paths-2.2.1" = {
      name = "env-paths";
      packageName = "env-paths";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/env-paths/-/env-paths-2.2.1.tgz";
        sha512 = "+h1lkLKhZMTYjog1VEpJNG7NZJWcuc2DDk/qsqSTRRCOXiLjeQ1d1/udrUGhqMxUgAlwKNZ0cf2uqan5GLuS2A==";
      };
    };
    "error-ex-1.3.2" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.2.tgz";
        sha512 = "7dFHNmqeFSEt2ZBsCriorKnn3Z2pj+fd9kmI6QoWw4//DL+icEBfc0U7qJCisqrTsKTjw4fNFy2pW9OqStD84g==";
      };
    };
    "es6-error-4.1.1" = {
      name = "es6-error";
      packageName = "es6-error";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-error/-/es6-error-4.1.1.tgz";
        sha512 = "Um/+FxMr9CISWh0bi5Zv0iOD+4cFh5qLeks1qhAopKVAJw3drgKbKySikp7wGhDL0HPeaja0P5ULZrxLkniUVg==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "escape-string-regexp-4.0.0" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-4.0.0.tgz";
        sha512 = "TtpcNJ3XAzx3Gq8sWRzJaVajRs0uVxA2YAkdb1jm2YkPz4G6egUFAyA3n5vtEIZefPk5Wa4UXbKuS5fKkJWdgA==";
      };
    };
    "extract-zip-2.0.1" = {
      name = "extract-zip";
      packageName = "extract-zip";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extract-zip/-/extract-zip-2.0.1.tgz";
        sha512 = "GDhU9ntwuKyGXdZBUgTIe+vXnWj0fppUEtMDL0+idd5Sta8TGpHssn/eusA9mrPr9qNDym6SxAYZjNvCn/9RBg==";
      };
    };
    "fd-slicer-1.1.0" = {
      name = "fd-slicer";
      packageName = "fd-slicer";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fd-slicer/-/fd-slicer-1.1.0.tgz";
        sha1 = "25c7c89cb1f9077f8891bbe61d8f390eae256f1e";
      };
    };
    "filename-reserved-regex-2.0.0" = {
      name = "filename-reserved-regex";
      packageName = "filename-reserved-regex";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/filename-reserved-regex/-/filename-reserved-regex-2.0.0.tgz";
        sha1 = "abf73dfab735d045440abfea2d91f389ebbfa229";
      };
    };
    "filenamify-4.2.0" = {
      name = "filenamify";
      packageName = "filenamify";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/filenamify/-/filenamify-4.2.0.tgz";
        sha512 = "pkgE+4p7N1n7QieOopmn3TqJaefjdWXwEkj2XLZJLKfOgcQKkn11ahvGNgTD8mLggexLiDFQxeTs14xVU22XPA==";
      };
    };
    "find-up-2.1.0" = {
      name = "find-up";
      packageName = "find-up";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-2.1.0.tgz";
        sha1 = "45d1b7e506c717ddd482775a2b77920a3c0c57a7";
      };
    };
    "flora-colossus-1.0.1" = {
      name = "flora-colossus";
      packageName = "flora-colossus";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/flora-colossus/-/flora-colossus-1.0.1.tgz";
        sha512 = "d+9na7t9FyH8gBJoNDSi28mE4NgQVGGvxQ4aHtFRetjyh5SXjuus+V5EZaxFmFdXVemSOrx0lsgEl/ZMjnOWJA==";
      };
    };
    "fs-extra-4.0.3" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-4.0.3.tgz";
        sha512 = "q6rbdDd1o2mAnQreO7YADIxf/Whx4AHBiRf6d+/cVT8h44ss+lHgxf1FemcqDnQt9X3ct4McHr+JMGlYSsK7Cg==";
      };
    };
    "fs-extra-7.0.1" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-7.0.1.tgz";
        sha512 = "YJDaCJZEnBmcbw13fvdAM9AwNOJwOzrE4pqMqBq5nFiEqXUqHwlK4B+3pUw6JNvfSPtX05xFHtYy/1ni01eGCw==";
      };
    };
    "fs-extra-8.1.0" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-8.1.0.tgz";
        sha512 = "yhlQgA6mnOJUKOsRUFsgJdQCvkKhcz8tlZG5HBQfReYZy46OwLcY+Zia0mtdHsOo9y/hP+CxMN0TU9QxoOtG4g==";
      };
    };
    "fs-extra-9.1.0" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "9.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-9.1.0.tgz";
        sha512 = "hcg3ZmepS30/7BSFqRvoo3DOMQu7IjqxO5nCDt+zM9XWjb33Wg7ziNT+Qvqbuc3+gWpzO02JubVyk2G4Zvo1OQ==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "galactus-0.2.1" = {
      name = "galactus";
      packageName = "galactus";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/galactus/-/galactus-0.2.1.tgz";
        sha1 = "cbed2d20a40c1f5679a35908e2b9415733e78db9";
      };
    };
    "get-package-info-1.0.0" = {
      name = "get-package-info";
      packageName = "get-package-info";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-package-info/-/get-package-info-1.0.0.tgz";
        sha1 = "6432796563e28113cd9474dbbd00052985a4999c";
      };
    };
    "get-stream-4.1.0" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-4.1.0.tgz";
        sha512 = "GMat4EJ5161kIy2HevLlr4luNjBgvmj413KaQA7jt4V8B4RDsfpHk7WQ9GVqfYyyx8OS/L66Kox+rJRNklLK7w==";
      };
    };
    "get-stream-5.2.0" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-5.2.0.tgz";
        sha512 = "nBF+F1rAZVCu/p7rjzgA+Yb4lfYXrpl7a6VmJrU8wF9I1CKvP/QwPNZHnOlwbTkY6dvtFIzFMSyQXbLoTQPRpA==";
      };
    };
    "glob-7.1.6" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.6.tgz";
        sha512 = "LwaxwyZ72Lk7vZINtNNrywX0ZuLyStrdDtabefZKAY5ZGJhVtgdznluResxNmPitE0SAO+O26sWTHeKSI2wMBA==";
      };
    };
    "global-agent-2.1.12" = {
      name = "global-agent";
      packageName = "global-agent";
      version = "2.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/global-agent/-/global-agent-2.1.12.tgz";
        sha512 = "caAljRMS/qcDo69X9BfkgrihGUgGx44Fb4QQToNQjsiWh+YlQ66uqYVAdA8Olqit+5Ng0nkz09je3ZzANMZcjg==";
      };
    };
    "global-tunnel-ng-2.7.1" = {
      name = "global-tunnel-ng";
      packageName = "global-tunnel-ng";
      version = "2.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/global-tunnel-ng/-/global-tunnel-ng-2.7.1.tgz";
        sha512 = "4s+DyciWBV0eK148wqXxcmVAbFVPqtc3sEtUE/GTQfuU80rySLcMhUmHKSHI7/LDj8q0gDYI1lIhRRB7ieRAqg==";
      };
    };
    "globalthis-1.0.2" = {
      name = "globalthis";
      packageName = "globalthis";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/globalthis/-/globalthis-1.0.2.tgz";
        sha512 = "ZQnSFO1la8P7auIOQECnm0sSuoMeaSq0EEdXMBFF2QJO4uNcwbyhSgG3MruWNbFTqCLmxVwGOl7LZ9kASvHdeQ==";
      };
    };
    "got-9.6.0" = {
      name = "got";
      packageName = "got";
      version = "9.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/got/-/got-9.6.0.tgz";
        sha512 = "R7eWptXuGYxwijs0eV+v3o6+XH1IqVK8dJOEecQfTmkncw9AV4dcw/Dhxi8MdlqPthxxpZyizMzyg8RTmEsG+Q==";
      };
    };
    "graceful-fs-4.2.6" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.6.tgz";
        sha512 = "nTnJ528pbqxYanhpDYsi4Rd8MAeaBA67+RZ10CM1m3bTAVFEDcd5AuA4a6W5YkGZ1iNXHzZz8T6TBKLeBuNriQ==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "hosted-git-info-2.8.8" = {
      name = "hosted-git-info";
      packageName = "hosted-git-info";
      version = "2.8.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-2.8.8.tgz";
        sha512 = "f/wzC2QaWBs7t9IYqB4T3sR1xviIViXJRJTWBlx2Gf3g0Xi5vI7Yy4koXQ1c9OYDGHN9sBy1DQ2AB8fqZBWhUg==";
      };
    };
    "http-cache-semantics-4.1.0" = {
      name = "http-cache-semantics";
      packageName = "http-cache-semantics";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-cache-semantics/-/http-cache-semantics-4.1.0.tgz";
        sha512 = "carPklcUh7ROWRK7Cv27RPtdhYhUsela/ue5/jKzjegVvXDqM2ILE9Q2BGn9JZJh1g87cp56su/FgQSzcWS8cQ==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ini-1.3.8" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.8.tgz";
        sha512 = "JV/yugV2uzW5iMRSiZAyDtQd+nxtUnjeLt0acNdw98kKLrvuRVyB80tsREOE7yvGVgalhZ6RNXCmEHkUKBKxew==";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha1 = "77c99840527aa8ecb1a8ba697b80645a7a926a9d";
      };
    };
    "is-core-module-2.2.0" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.2.0.tgz";
        sha512 = "XRAfAdyyY5F5cOXn7hYQDqh2Xmii+DEfIcQGxK/uNwMHhIkPWO0g8msXcbzLe+MpGoR951MlqM/2iIlU4vKDdQ==";
      };
    };
    "isbinaryfile-3.0.3" = {
      name = "isbinaryfile";
      packageName = "isbinaryfile";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/isbinaryfile/-/isbinaryfile-3.0.3.tgz";
        sha512 = "8cJBL5tTd2OS0dM4jz07wQd5g0dCCqIhUxPIGtZfa5L6hWlvV5MHTITy/DBAsF+Oe2LS1X3krBUhNwaGUWpWxw==";
      };
    };
    "json-buffer-3.0.0" = {
      name = "json-buffer";
      packageName = "json-buffer";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-buffer/-/json-buffer-3.0.0.tgz";
        sha1 = "5b1f397afc75d677bde8bcfc0e47e1f9a3d9a898";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "jsonfile-4.0.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-4.0.0.tgz";
        sha1 = "8771aae0799b64076b76640fca058f9c10e33ecb";
      };
    };
    "jsonfile-6.1.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-6.1.0.tgz";
        sha512 = "5dgndWOriYSm5cnYaJNhalLNDKOqFwyDB/rr1E9ZsGciGvKPs8R2xYGCacuf3z6K1YKDz182fd+fY3cn3pMqXQ==";
      };
    };
    "junk-3.1.0" = {
      name = "junk";
      packageName = "junk";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/junk/-/junk-3.1.0.tgz";
        sha512 = "pBxcB3LFc8QVgdggvZWyeys+hnrNWg4OcZIU/1X59k5jQdLBlCsYGRQaz234SqoRLTCgMH00fY0xRJH+F9METQ==";
      };
    };
    "keyboardevent-from-electron-accelerator-2.0.0" = {
      name = "keyboardevent-from-electron-accelerator";
      packageName = "keyboardevent-from-electron-accelerator";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/keyboardevent-from-electron-accelerator/-/keyboardevent-from-electron-accelerator-2.0.0.tgz";
        sha512 = "iQcmNA0M4ETMNi0kG/q0h/43wZk7rMeKYrXP7sqKIJbHkTU8Koowgzv+ieR/vWJbOwxx5nDC3UnudZ0aLSu4VA==";
      };
    };
    "keyboardevents-areequal-0.2.2" = {
      name = "keyboardevents-areequal";
      packageName = "keyboardevents-areequal";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/keyboardevents-areequal/-/keyboardevents-areequal-0.2.2.tgz";
        sha512 = "Nv+Kr33T0mEjxR500q+I6IWisOQ0lK1GGOncV0kWE6n4KFmpcu7RUX5/2B0EUtX51Cb0HjZ9VJsSY3u4cBa0kw==";
      };
    };
    "keyv-3.1.0" = {
      name = "keyv";
      packageName = "keyv";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/keyv/-/keyv-3.1.0.tgz";
        sha512 = "9ykJ/46SN/9KPM/sichzQ7OvXyGDYKGTaDlKMGCAlg2UK8KRy4jb0d8sFc+0Tt0YYnThq8X2RZgCg74RPxgcVA==";
      };
    };
    "load-json-file-2.0.0" = {
      name = "load-json-file";
      packageName = "load-json-file";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/load-json-file/-/load-json-file-2.0.0.tgz";
        sha1 = "7947e42149af80d696cbf797bcaabcfe1fe29ca8";
      };
    };
    "locate-path-2.0.0" = {
      name = "locate-path";
      packageName = "locate-path";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-path/-/locate-path-2.0.0.tgz";
        sha1 = "2b568b265eec944c6d9c0de9c3dbbbca0354cd8e";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lodash.get-4.4.2" = {
      name = "lodash.get";
      packageName = "lodash.get";
      version = "4.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.get/-/lodash.get-4.4.2.tgz";
        sha1 = "2d177f652fa31e939b4438d5341499dfa3825e99";
      };
    };
    "lowercase-keys-1.0.1" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-1.0.1.tgz";
        sha512 = "G2Lj61tXDnVFFOi8VZds+SoQjtQC3dgokKdDG2mTm1tx4m50NUHBOZSBwQQHyy0V12A0JTG4icfZQH+xPyh8VA==";
      };
    };
    "lowercase-keys-2.0.0" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-2.0.0.tgz";
        sha512 = "tqNXrS78oMOE73NMxK4EMLQsQowWf8jKooH9g7xPavRT706R6bkQJ6DY2Te7QukaZsulxa30wQ7bk0pm4XiHmA==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "matcher-3.0.0" = {
      name = "matcher";
      packageName = "matcher";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/matcher/-/matcher-3.0.0.tgz";
        sha512 = "OkeDaAZ/bQCxeFAozM55PKcKU0yJMPGifLwV4Qgjitu+5MoAfSQN4lsLJeXZ1b8w0x+/Emda6MZgXS1jvsapng==";
      };
    };
    "mimic-response-1.0.1" = {
      name = "mimic-response";
      packageName = "mimic-response";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-response/-/mimic-response-1.0.1.tgz";
        sha512 = "j5EctnkH7amfV/q5Hgmoal1g2QHFJRraOtmx0JpIqkxhBhI/lJSl1nMpQ45hVarwNETOoWEimndZ4QK0RHxuxQ==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-1.2.5" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz";
        sha512 = "FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "normalize-package-data-2.5.0" = {
      name = "normalize-package-data";
      packageName = "normalize-package-data";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-package-data/-/normalize-package-data-2.5.0.tgz";
        sha512 = "/5CMN3T0R4XTj4DcGaexo+roZSdSFW/0AOOTROrjxzCG1wrWXEsGbRKevjlIL+ZDE4sZlJr5ED4YW0yqmkK+eA==";
      };
    };
    "normalize-url-4.5.0" = {
      name = "normalize-url";
      packageName = "normalize-url";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-url/-/normalize-url-4.5.0.tgz";
        sha512 = "2s47yzUxdexf1OhyRi4Em83iQk0aPvwTddtFz4hnSSw9dCEsLEGf6SwIO8ss/19S9iBb5sJaOuTvTGDeZI00BQ==";
      };
    };
    "npm-conf-1.1.3" = {
      name = "npm-conf";
      packageName = "npm-conf";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-conf/-/npm-conf-1.1.3.tgz";
        sha512 = "Yic4bZHJOt9RCFbRP3GgpqhScOY4HH3V2P8yBj6CeYq118Qr+BLXqT2JvpJ00mryLESpgOxf5XlFv4ZjXxLScw==";
      };
    };
    "object-keys-1.1.1" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz";
        sha512 = "NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "p-cancelable-1.1.0" = {
      name = "p-cancelable";
      packageName = "p-cancelable";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-cancelable/-/p-cancelable-1.1.0.tgz";
        sha512 = "s73XxOZ4zpt1edZYZzvhqFa6uvQc1vwUa0K0BdtIZgQMAJj9IbebH+JkgKZc9h+B05PKHLOTl4ajG1BmNrVZlw==";
      };
    };
    "p-limit-1.3.0" = {
      name = "p-limit";
      packageName = "p-limit";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-1.3.0.tgz";
        sha512 = "vvcXsLAJ9Dr5rQOPk7toZQZJApBl2K4J6dANSsEuh6QI41JYcsS/qhTGa9ErIUUgK3WNQoJYvylxvjqmiqEA9Q==";
      };
    };
    "p-locate-2.0.0" = {
      name = "p-locate";
      packageName = "p-locate";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-locate/-/p-locate-2.0.0.tgz";
        sha1 = "20a0103b222a70c8fd39cc2e580680f3dde5ec43";
      };
    };
    "p-try-1.0.0" = {
      name = "p-try";
      packageName = "p-try";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-try/-/p-try-1.0.0.tgz";
        sha1 = "cbc79cdbaf8fd4228e13f621f2b1a237c1b207b3";
      };
    };
    "parse-author-2.0.0" = {
      name = "parse-author";
      packageName = "parse-author";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-author/-/parse-author-2.0.0.tgz";
        sha1 = "d3460bf1ddd0dfaeed42da754242e65fb684a81f";
      };
    };
    "parse-json-2.2.0" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-2.2.0.tgz";
        sha1 = "f480f40434ef80741f8469099f8dea18f55a4dc9";
      };
    };
    "path-exists-3.0.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-3.0.0.tgz";
        sha1 = "ce0ebeaa5f78cb18925ea7d810d7b59b010fd515";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-parse-1.0.6" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.6.tgz";
        sha512 = "GSmOT2EbHrINBf9SR7CDELwlJ8AENk3Qn7OikK4nFYAu3Ote2+JYNVvkpAEQm3/TLNEJFD/xZJjzyxg3KBWOzw==";
      };
    };
    "path-type-2.0.0" = {
      name = "path-type";
      packageName = "path-type";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-type/-/path-type-2.0.0.tgz";
        sha1 = "f012ccb8415b7096fc2daa1054c3d72389594c73";
      };
    };
    "pend-1.2.0" = {
      name = "pend";
      packageName = "pend";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pend/-/pend-1.2.0.tgz";
        sha1 = "7a57eb550a6783f9115331fcf4663d5c8e007a50";
      };
    };
    "pify-2.3.0" = {
      name = "pify";
      packageName = "pify";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-2.3.0.tgz";
        sha1 = "ed141a6ac043a849ea588498e7dca8b15330e90c";
      };
    };
    "pify-3.0.0" = {
      name = "pify";
      packageName = "pify";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-3.0.0.tgz";
        sha1 = "e5a4acd2c101fdf3d9a4d07f0dbc4db49dd28176";
      };
    };
    "plist-3.0.1" = {
      name = "plist";
      packageName = "plist";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/plist/-/plist-3.0.1.tgz";
        sha512 = "GpgvHHocGRyQm74b6FWEZZVRroHKE1I0/BTjAmySaohK+cUn+hZpbqXkc3KWgW3gQYkqcQej35FohcT0FRlkRQ==";
      };
    };
    "prepend-http-2.0.0" = {
      name = "prepend-http";
      packageName = "prepend-http";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prepend-http/-/prepend-http-2.0.0.tgz";
        sha1 = "e92434bfa5ea8c19f41cdfd401d741a3c819d897";
      };
    };
    "progress-2.0.3" = {
      name = "progress";
      packageName = "progress";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/progress/-/progress-2.0.3.tgz";
        sha512 = "7PiHtLll5LdnKIMw100I+8xJXR5gW2QwWYkT6iJva0bXitZKa/XMrSbdmg3r2Xnaidz9Qumd0VPaMrZlF9V9sA==";
      };
    };
    "proto-list-1.2.4" = {
      name = "proto-list";
      packageName = "proto-list";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/proto-list/-/proto-list-1.2.4.tgz";
        sha1 = "212d5bfe1318306a420f6402b8e26ff39647a849";
      };
    };
    "pump-3.0.0" = {
      name = "pump";
      packageName = "pump";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pump/-/pump-3.0.0.tgz";
        sha512 = "LwZy+p3SFs1Pytd/jYct4wpv49HiYCqd9Rlc5ZVdk0V+8Yzv6jR5Blk3TRmPL1ft69TxP0IMZGJ+WPFU2BFhww==";
      };
    };
    "rcedit-2.3.0" = {
      name = "rcedit";
      packageName = "rcedit";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rcedit/-/rcedit-2.3.0.tgz";
        sha512 = "h1gNEl9Oai1oijwyJ1WYqYSXTStHnOcv1KYljg/8WM4NAg3H1KBK3azIaKkQ1WQl+d7PoJpcBMscPfLXVKgCLQ==";
      };
    };
    "read-pkg-2.0.0" = {
      name = "read-pkg";
      packageName = "read-pkg";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg/-/read-pkg-2.0.0.tgz";
        sha1 = "8ef1c0623c6a6db0dc6713c4bfac46332b2368f8";
      };
    };
    "read-pkg-up-2.0.0" = {
      name = "read-pkg-up";
      packageName = "read-pkg-up";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg-up/-/read-pkg-up-2.0.0.tgz";
        sha1 = "6b72a8048984e0c41e79510fd5e9fa99b3b549be";
      };
    };
    "resolve-1.20.0" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.20.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.20.0.tgz";
        sha512 = "wENBPt4ySzg4ybFQW2TT1zMQucPK95HSh/nq2CFTZVOGut2+pQvSsgtda4d26YrYcr067wjbmzOG8byDPBX63A==";
      };
    };
    "responselike-1.0.2" = {
      name = "responselike";
      packageName = "responselike";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/responselike/-/responselike-1.0.2.tgz";
        sha1 = "918720ef3b631c5642be068f15ade5a46f4ba1e7";
      };
    };
    "roarr-2.15.4" = {
      name = "roarr";
      packageName = "roarr";
      version = "2.15.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/roarr/-/roarr-2.15.4.tgz";
        sha512 = "CHhPh+UNHD2GTXNYhPWLnU8ONHdI+5DI+4EYIAOaiD63rHeYlZvyh8P+in5999TTSFgUYuKUAjzRI4mdh/p+2A==";
      };
    };
    "semver-5.7.1" = {
      name = "semver";
      packageName = "semver";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.7.1.tgz";
        sha512 = "sauaDf/PZdVgrLTNYHRtpXa1iRiKcaebiKQ1BJdpQlWH2lCvexQdX55snPFyK7QzpudqbCI0qXFfOasHdyNDGQ==";
      };
    };
    "semver-6.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.0.tgz";
        sha512 = "b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw==";
      };
    };
    "semver-7.3.5" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.5.tgz";
        sha512 = "PoeGJYh8HK4BTO/a9Tf6ZG3veo/A7ZVsYrSA6J8ny9nb3B1VrpkuN+z9OE5wfE5p6H4LchYZsegiQgbJD94ZFQ==";
      };
    };
    "semver-compare-1.0.0" = {
      name = "semver-compare";
      packageName = "semver-compare";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver-compare/-/semver-compare-1.0.0.tgz";
        sha1 = "0dee216a1c941ab37e9efb1788f6afc5ff5537fc";
      };
    };
    "serialize-error-7.0.1" = {
      name = "serialize-error";
      packageName = "serialize-error";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/serialize-error/-/serialize-error-7.0.1.tgz";
        sha512 = "8I8TjW5KMOKsZQTvoxjuSIa7foAwPWGOts+6o7sgjz41/qMD9VQHEDxi6PBvK2l0MXUmqZyNpUK+T2tQaaElvw==";
      };
    };
    "spdx-correct-3.1.1" = {
      name = "spdx-correct";
      packageName = "spdx-correct";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-correct/-/spdx-correct-3.1.1.tgz";
        sha512 = "cOYcUWwhCuHCXi49RhFRCyJEK3iPj1Ziz9DpViV3tbZOwXD49QzIN3MpOLJNxh2qwq2lJJZaKMVw9qNi4jTC0w==";
      };
    };
    "spdx-exceptions-2.3.0" = {
      name = "spdx-exceptions";
      packageName = "spdx-exceptions";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-exceptions/-/spdx-exceptions-2.3.0.tgz";
        sha512 = "/tTrYOC7PPI1nUAgx34hUpqXuyJG+DTHJTnIULG4rDygi4xu/tfgmq1e1cIRwRzwZgo4NLySi+ricLkZkw4i5A==";
      };
    };
    "spdx-expression-parse-3.0.1" = {
      name = "spdx-expression-parse";
      packageName = "spdx-expression-parse";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-expression-parse/-/spdx-expression-parse-3.0.1.tgz";
        sha512 = "cbqHunsQWnJNE6KhVSMsMeH5H/L9EpymbzqTQ3uLwNCLZ1Q481oWaofqH7nO6V07xlXwY6PhQdQ2IedWx/ZK4Q==";
      };
    };
    "spdx-license-ids-3.0.7" = {
      name = "spdx-license-ids";
      packageName = "spdx-license-ids";
      version = "3.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-license-ids/-/spdx-license-ids-3.0.7.tgz";
        sha512 = "U+MTEOO0AiDzxwFvoa4JVnMV6mZlJKk2sBLt90s7G0Gd0Mlknc7kxEn3nuDPNZRta7O2uy8oLcZLVT+4sqNZHQ==";
      };
    };
    "sprintf-js-1.1.2" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.1.2.tgz";
        sha512 = "VE0SOVEHCk7Qc8ulkWw3ntAzXuqf7S2lvwQaDLRnUeIEaKNQJzV6BwmLKhOqT61aGhfUMrXeaBk+oDGCzvhcug==";
      };
    };
    "strip-bom-3.0.0" = {
      name = "strip-bom";
      packageName = "strip-bom";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-bom/-/strip-bom-3.0.0.tgz";
        sha1 = "2334c18e9c759f7bdd56fdef7e9ae3d588e68ed3";
      };
    };
    "strip-outer-1.0.1" = {
      name = "strip-outer";
      packageName = "strip-outer";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-outer/-/strip-outer-1.0.1.tgz";
        sha512 = "k55yxKHwaXnpYGsOzg4Vl8+tDrWylxDEpknGjhTiZB8dFRU5rTo9CAzeycivxV3s+zlTKwrs6WxMxR95n26kwg==";
      };
    };
    "sumchecker-3.0.1" = {
      name = "sumchecker";
      packageName = "sumchecker";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sumchecker/-/sumchecker-3.0.1.tgz";
        sha512 = "MvjXzkz/BOfyVDkG0oFOtBxHX2u3gKbMHIF/dXblZsgD3BWOFLmHovIpZY7BykJdAjcqRCBi1WYBNdEC9yI7vg==";
      };
    };
    "to-readable-stream-1.0.0" = {
      name = "to-readable-stream";
      packageName = "to-readable-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-readable-stream/-/to-readable-stream-1.0.0.tgz";
        sha512 = "Iq25XBt6zD5npPhlLVXGFN3/gyR2/qODcKNNyTMd4vbm39HUaOiAM4PMq0eMVC/Tkxz+Zjdsc55g9yyz+Yq00Q==";
      };
    };
    "trim-repeated-1.0.0" = {
      name = "trim-repeated";
      packageName = "trim-repeated";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/trim-repeated/-/trim-repeated-1.0.0.tgz";
        sha1 = "e3646a2ea4e891312bf7eace6cfb05380bc01c21";
      };
    };
    "tunnel-0.0.6" = {
      name = "tunnel";
      packageName = "tunnel";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel/-/tunnel-0.0.6.tgz";
        sha512 = "1h/Lnq9yajKY2PEbBadPXj3VxsDDu844OnaAo52UVmIzIvwwtBPIuNvkjuzBlTWpfJyUbG3ez0KSBibQkj4ojg==";
      };
    };
    "type-fest-0.13.1" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "0.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-0.13.1.tgz";
        sha512 = "34R7HTnG0XIJcBSn5XhDd7nNFPRcXYRZrBB2O2jdKqYODldSzBAqzsWoZYYvduky73toYS/ESqxPvkDf/F0XMg==";
      };
    };
    "universalify-0.1.2" = {
      name = "universalify";
      packageName = "universalify";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-0.1.2.tgz";
        sha512 = "rBJeI5CXAlmy1pV+617WB9J63U6XcazHHF2f2dbJix4XzpUF0RS3Zbj0FGIOCAva5P/d/GBOYaACQ1w+0azUkg==";
      };
    };
    "universalify-2.0.0" = {
      name = "universalify";
      packageName = "universalify";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-2.0.0.tgz";
        sha512 = "hAZsKq7Yy11Zu1DE0OzWjw7nnLZmJZYTDZZyEFHZdUhV8FkH5MCfoU1XMaxXovpyW5nq5scPqq0ZDP9Zyl04oQ==";
      };
    };
    "url-parse-lax-3.0.0" = {
      name = "url-parse-lax";
      packageName = "url-parse-lax";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-parse-lax/-/url-parse-lax-3.0.0.tgz";
        sha1 = "16b5cafc07dbe3676c1b1999177823d6503acb0c";
      };
    };
    "validate-npm-package-license-3.0.4" = {
      name = "validate-npm-package-license";
      packageName = "validate-npm-package-license";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/validate-npm-package-license/-/validate-npm-package-license-3.0.4.tgz";
        sha512 = "DpKm2Ui/xN7/HQKCtpZxoRWBhZ9Z0kqtygG8XCgNQ8ZlDnxuQmWhj566j8fN4Cu3/JmbhsDo7fcAJq4s9h27Ew==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "ws-7.4.4" = {
      name = "ws";
      packageName = "ws";
      version = "7.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.4.4.tgz";
        sha512 = "Qm8k8ojNQIMx7S+Zp8u/uHOx7Qazv3Yv4q68MiWWWOJhiwG5W3x7iqmRtJo8xxrciZUY4vRxUTJCKuRnF28ZZw==";
      };
    };
    "xmlbuilder-9.0.7" = {
      name = "xmlbuilder";
      packageName = "xmlbuilder";
      version = "9.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-9.0.7.tgz";
        sha1 = "132ee63d2ec5565c557e20f4c22df9aca686b10d";
      };
    };
    "xmldom-0.1.31" = {
      name = "xmldom";
      packageName = "xmldom";
      version = "0.1.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmldom/-/xmldom-0.1.31.tgz";
        sha512 = "yS2uJflVQs6n+CyjHoaBmVSqIDevTAWrzMmjG1Gc7h1qQ7uVozNhEPJAwZXWyGQ/Gafo3fCwrcaokezLPupVyQ==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
    "yargs-parser-20.2.7" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "20.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-20.2.7.tgz";
        sha512 = "FiNkvbeHzB/syOjIUxFDCnhSfzAL8R5vs40MgLFBorXACCOAEaWu0gRZl14vG8MR9AOJIZbmkjhusqBYZ3HTHw==";
      };
    };
    "yauzl-2.10.0" = {
      name = "yauzl";
      packageName = "yauzl";
      version = "2.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yauzl/-/yauzl-2.10.0.tgz";
        sha1 = "c7eb17c93e112cb1086fa6d8e51fb0667b79a5f9";
      };
    };
  };
  args = {
    name = "TeleDrive";
    packageName = "TeleDrive";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      (sources."@electron/get-1.12.4" // {
        dependencies = [
          sources."fs-extra-8.1.0"
          sources."jsonfile-4.0.0"
          sources."semver-6.3.0"
          sources."universalify-0.1.2"
        ];
      })
      sources."@sindresorhus/is-0.14.0"
      sources."@szmarczak/http-timer-1.1.2"
      sources."@types/glob-7.1.3"
      sources."@types/minimatch-3.0.3"
      sources."@types/node-14.14.35"
      sources."@types/yauzl-2.9.1"
      (sources."asar-3.0.3" // {
        dependencies = [
          sources."commander-5.1.0"
        ];
      })
      sources."at-least-node-1.0.0"
      sources."author-regex-1.0.0"
      sources."balanced-match-1.0.0"
      sources."base64-js-1.5.1"
      sources."bluebird-3.7.2"
      sources."boolean-3.0.2"
      sources."brace-expansion-1.1.11"
      sources."buffer-alloc-1.2.0"
      sources."buffer-alloc-unsafe-1.1.0"
      sources."buffer-crc32-0.2.13"
      sources."buffer-fill-1.0.0"
      (sources."cacheable-request-6.1.0" // {
        dependencies = [
          sources."get-stream-5.2.0"
          sources."lowercase-keys-2.0.0"
        ];
      })
      sources."chromium-pickle-js-0.2.0"
      sources."clone-response-1.0.2"
      sources."compare-version-0.1.2"
      sources."concat-map-0.0.1"
      sources."config-chain-1.1.12"
      sources."core-js-3.9.1"
      sources."debug-4.3.2"
      sources."decompress-response-3.3.0"
      sources."defer-to-connect-1.1.3"
      sources."define-properties-1.1.3"
      sources."detect-node-2.0.5"
      sources."duplexer3-0.1.4"
      sources."electron-is-accelerator-0.1.2"
      sources."electron-localshortcut-3.2.1"
      sources."electron-notarize-1.0.0"
      (sources."electron-osx-sign-0.5.0" // {
        dependencies = [
          sources."debug-2.6.9"
          sources."ms-2.0.0"
        ];
      })
      (sources."electron-packager-15.2.0" // {
        dependencies = [
          sources."extract-zip-2.0.1"
          sources."get-stream-5.2.0"
        ];
      })
      (sources."electron-squirrel-startup-1.0.0" // {
        dependencies = [
          sources."debug-2.6.9"
          sources."ms-2.0.0"
        ];
      })
      sources."encodeurl-1.0.2"
      sources."end-of-stream-1.4.4"
      sources."env-paths-2.2.1"
      sources."error-ex-1.3.2"
      sources."es6-error-4.1.1"
      sources."escape-string-regexp-1.0.5"
      sources."fd-slicer-1.1.0"
      sources."filename-reserved-regex-2.0.0"
      sources."filenamify-4.2.0"
      (sources."flora-colossus-1.0.1" // {
        dependencies = [
          sources."fs-extra-7.0.1"
          sources."jsonfile-4.0.0"
          sources."universalify-0.1.2"
        ];
      })
      sources."fs-extra-9.1.0"
      sources."fs.realpath-1.0.0"
      sources."function-bind-1.1.1"
      (sources."galactus-0.2.1" // {
        dependencies = [
          sources."debug-3.2.7"
          sources."fs-extra-4.0.3"
          sources."jsonfile-4.0.0"
          sources."universalify-0.1.2"
        ];
      })
      (sources."get-package-info-1.0.0" // {
        dependencies = [
          sources."debug-2.6.9"
          sources."ms-2.0.0"
        ];
      })
      sources."get-stream-4.1.0"
      sources."glob-7.1.6"
      sources."global-agent-2.1.12"
      sources."global-tunnel-ng-2.7.1"
      sources."globalthis-1.0.2"
      sources."got-9.6.0"
      sources."graceful-fs-4.2.6"
      sources."has-1.0.3"
      sources."hosted-git-info-2.8.8"
      sources."http-cache-semantics-4.1.0"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."ini-1.3.8"
      sources."is-arrayish-0.2.1"
      sources."is-core-module-2.2.0"
      sources."isbinaryfile-3.0.3"
      sources."json-buffer-3.0.0"
      sources."json-stringify-safe-5.0.1"
      sources."jsonfile-6.1.0"
      sources."junk-3.1.0"
      sources."keyboardevent-from-electron-accelerator-2.0.0"
      sources."keyboardevents-areequal-0.2.2"
      sources."keyv-3.1.0"
      (sources."load-json-file-2.0.0" // {
        dependencies = [
          sources."pify-2.3.0"
        ];
      })
      sources."lodash-4.17.21"
      sources."lodash.get-4.4.2"
      sources."lowercase-keys-1.0.1"
      sources."lru-cache-6.0.0"
      (sources."matcher-3.0.0" // {
        dependencies = [
          sources."escape-string-regexp-4.0.0"
        ];
      })
      sources."mimic-response-1.0.1"
      sources."minimatch-3.0.4"
      sources."minimist-1.2.5"
      sources."ms-2.1.2"
      (sources."normalize-package-data-2.5.0" // {
        dependencies = [
          sources."semver-5.7.1"
        ];
      })
      sources."normalize-url-4.5.0"
      sources."npm-conf-1.1.3"
      sources."object-keys-1.1.1"
      sources."once-1.4.0"
      sources."p-cancelable-1.1.0"
      sources."parse-author-2.0.0"
      sources."parse-json-2.2.0"
      sources."path-is-absolute-1.0.1"
      sources."path-parse-1.0.6"
      (sources."path-type-2.0.0" // {
        dependencies = [
          sources."pify-2.3.0"
        ];
      })
      sources."pend-1.2.0"
      sources."pify-3.0.0"
      sources."plist-3.0.1"
      sources."prepend-http-2.0.0"
      sources."progress-2.0.3"
      sources."proto-list-1.2.4"
      sources."pump-3.0.0"
      sources."rcedit-2.3.0"
      sources."read-pkg-2.0.0"
      (sources."read-pkg-up-2.0.0" // {
        dependencies = [
          sources."find-up-2.1.0"
          sources."locate-path-2.0.0"
          sources."p-limit-1.3.0"
          sources."p-locate-2.0.0"
          sources."p-try-1.0.0"
          sources."path-exists-3.0.0"
        ];
      })
      sources."resolve-1.20.0"
      sources."responselike-1.0.2"
      sources."roarr-2.15.4"
      sources."semver-7.3.5"
      sources."semver-compare-1.0.0"
      (sources."serialize-error-7.0.1" // {
        dependencies = [
          sources."type-fest-0.13.1"
        ];
      })
      sources."spdx-correct-3.1.1"
      sources."spdx-exceptions-2.3.0"
      sources."spdx-expression-parse-3.0.1"
      sources."spdx-license-ids-3.0.7"
      sources."sprintf-js-1.1.2"
      sources."strip-bom-3.0.0"
      sources."strip-outer-1.0.1"
      sources."sumchecker-3.0.1"
      sources."to-readable-stream-1.0.0"
      sources."trim-repeated-1.0.0"
      sources."tunnel-0.0.6"
      sources."universalify-2.0.0"
      sources."url-parse-lax-3.0.0"
      sources."validate-npm-package-license-3.0.4"
      sources."wrappy-1.0.2"
      sources."ws-7.4.4"
      sources."xmlbuilder-9.0.7"
      sources."xmldom-0.1.31"
      sources."yallist-4.0.0"
      sources."yargs-parser-20.2.7"
      sources."yauzl-2.10.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Host Relay Server to Forward Gamepad Commands to the FTC Robot";
      license = "CC0-1.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
